#include "entrance_table.h"

// Entrance Table
//
// Copy of the vanilla entrance table, populated at patch time (1556 entries)
// Additional entries are appended for grotto entrances and exits
//
// See cloudmodding for table format: https://wiki.cloudmodding.com/oot/Entrance_Table
// New entrances must have a minimum of four entries appended to work with the entrance system.
// Each entry is 4 bytes.


EntranceInfo gExtendedEntranceTable[EXTENDED_TABLE_SIZE] = {
/* 000 */   [0 ... VANILLA_ENTRIES - 1] = 0, // Allocate space for vanilla entries

            // ******************************************************************************************************************
            // Small Fairy Fountains
            // ******************************************************************************************************************
            // Zora River (exit table index 0x05)
/* 614 */   [VANILLA_ENTRIES +   0] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 615 */   [VANILLA_ENTRIES +   1] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 616 */   [VANILLA_ENTRIES +   2] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 617 */   [VANILLA_ENTRIES +   3] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

/* 618 */   [VANILLA_ENTRIES +   4] = DEFINE_ENTRANCE(SCENE_ZORAS_RIVER, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 619 */   [VANILLA_ENTRIES +   5] = DEFINE_ENTRANCE(SCENE_ZORAS_RIVER, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 61A */   [VANILLA_ENTRIES +   6] = DEFINE_ENTRANCE(SCENE_ZORAS_RIVER, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 61B */   [VANILLA_ENTRIES +   7] = DEFINE_ENTRANCE(SCENE_ZORAS_RIVER, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Hyrule Field (exit table index 0x10)
/* 61C */   [VANILLA_ENTRIES +   8] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 61D */   [VANILLA_ENTRIES +   9] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 61E */   [VANILLA_ENTRIES +  10] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 61F */   [VANILLA_ENTRIES +  11] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

/* 620 */   [VANILLA_ENTRIES +  12] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x12, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 621 */   [VANILLA_ENTRIES +  13] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x12, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 622 */   [VANILLA_ENTRIES +  14] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x12, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 623 */   [VANILLA_ENTRIES +  15] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x12, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Sacred Forest Meadow (exit table index 0x02)
            // Child entrance index assumes that the child layer has the Phantom Ganon blue warp entrance added
/* 624 */   [VANILLA_ENTRIES +  16] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 625 */   [VANILLA_ENTRIES +  17] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 626 */   [VANILLA_ENTRIES +  18] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 627 */   [VANILLA_ENTRIES +  19] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

/* 628 */   [VANILLA_ENTRIES +  20] = DEFINE_ENTRANCE(SCENE_SACRED_FOREST_MEADOW, 0x04, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 629 */   [VANILLA_ENTRIES +  21] = DEFINE_ENTRANCE(SCENE_SACRED_FOREST_MEADOW, 0x04, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 62A */   [VANILLA_ENTRIES +  22] = DEFINE_ENTRANCE(SCENE_SACRED_FOREST_MEADOW, 0x04, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 62B */   [VANILLA_ENTRIES +  23] = DEFINE_ENTRANCE(SCENE_SACRED_FOREST_MEADOW, 0x04, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Zora's Domain (exit table index 0x04)
/* 62C */   [VANILLA_ENTRIES +  24] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 62D */   [VANILLA_ENTRIES +  25] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 62E */   [VANILLA_ENTRIES +  26] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 62F */   [VANILLA_ENTRIES +  27] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

/* 630 */   [VANILLA_ENTRIES +  28] = DEFINE_ENTRANCE(SCENE_ZORAS_DOMAIN, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 631 */   [VANILLA_ENTRIES +  29] = DEFINE_ENTRANCE(SCENE_ZORAS_DOMAIN, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 632 */   [VANILLA_ENTRIES +  30] = DEFINE_ENTRANCE(SCENE_ZORAS_DOMAIN, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 633 */   [VANILLA_ENTRIES +  31] = DEFINE_ENTRANCE(SCENE_ZORAS_DOMAIN, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Gerudo Fortress (exit table index 0x10)
/* 634 */   [VANILLA_ENTRIES +  32] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 635 */   [VANILLA_ENTRIES +  33] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 636 */   [VANILLA_ENTRIES +  34] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 637 */   [VANILLA_ENTRIES +  35] = DEFINE_ENTRANCE(SCENE_FAIRYS_FOUNTAIN, 0, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

/* 638 */   [VANILLA_ENTRIES +  36] = DEFINE_ENTRANCE(SCENE_GERUDOS_FORTRESS, 0x12, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 639 */   [VANILLA_ENTRIES +  37] = DEFINE_ENTRANCE(SCENE_GERUDOS_FORTRESS, 0x12, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 63A */   [VANILLA_ENTRIES +  38] = DEFINE_ENTRANCE(SCENE_GERUDOS_FORTRESS, 0x13, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 63B */   [VANILLA_ENTRIES +  39] = DEFINE_ENTRANCE(SCENE_GERUDOS_FORTRESS, 0x13, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // ******************************************************************************************************************
            // Generic Grottos
            // ******************************************************************************************************************
            // Zora River (exit table index 0x06)
/* 63C */   [VANILLA_ENTRIES +  40] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 63D */   [VANILLA_ENTRIES +  41] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 63E */   [VANILLA_ENTRIES +  42] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 63F */   [VANILLA_ENTRIES +  43] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

/* 640 */   [VANILLA_ENTRIES +  44] = DEFINE_ENTRANCE(SCENE_ZORAS_RIVER, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 641 */   [VANILLA_ENTRIES +  45] = DEFINE_ENTRANCE(SCENE_ZORAS_RIVER, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 642 */   [VANILLA_ENTRIES +  46] = DEFINE_ENTRANCE(SCENE_ZORAS_RIVER, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 643 */   [VANILLA_ENTRIES +  47] = DEFINE_ENTRANCE(SCENE_ZORAS_RIVER, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Death Mountain Crater (exit table index 0x04)
            // Child entrance index assumes that the child layer has the Volvagia blue warp entrance added
/* 644 */   [VANILLA_ENTRIES +  48] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 645 */   [VANILLA_ENTRIES +  49] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 646 */   [VANILLA_ENTRIES +  50] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 647 */   [VANILLA_ENTRIES +  51] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

/* 648 */   [VANILLA_ENTRIES +  52] = DEFINE_ENTRANCE(SCENE_DEATH_MOUNTAIN_CRATER, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 649 */   [VANILLA_ENTRIES +  53] = DEFINE_ENTRANCE(SCENE_DEATH_MOUNTAIN_CRATER, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 64A */   [VANILLA_ENTRIES +  54] = DEFINE_ENTRANCE(SCENE_DEATH_MOUNTAIN_CRATER, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 64B */   [VANILLA_ENTRIES +  55] = DEFINE_ENTRANCE(SCENE_DEATH_MOUNTAIN_CRATER, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Death Mountain Trail (exit table index 0x06)
/* 64C */   [VANILLA_ENTRIES +  56] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 64D */   [VANILLA_ENTRIES +  57] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 64E */   [VANILLA_ENTRIES +  58] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 64F */   [VANILLA_ENTRIES +  59] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

/* 650 */   [VANILLA_ENTRIES +  60] = DEFINE_ENTRANCE(SCENE_DEATH_MOUNTAIN_TRAIL, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 651 */   [VANILLA_ENTRIES +  61] = DEFINE_ENTRANCE(SCENE_DEATH_MOUNTAIN_TRAIL, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 652 */   [VANILLA_ENTRIES +  62] = DEFINE_ENTRANCE(SCENE_DEATH_MOUNTAIN_TRAIL, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 653 */   [VANILLA_ENTRIES +  63] = DEFINE_ENTRANCE(SCENE_DEATH_MOUNTAIN_TRAIL, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Kakariko Village (exit table index 0x0E)
/* 654 */   [VANILLA_ENTRIES +  64] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 655 */   [VANILLA_ENTRIES +  65] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 656 */   [VANILLA_ENTRIES +  66] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 657 */   [VANILLA_ENTRIES +  67] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

/* 658 */   [VANILLA_ENTRIES +  68] = DEFINE_ENTRANCE(SCENE_KAKARIKO_VILLAGE, 0x10, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 659 */   [VANILLA_ENTRIES +  69] = DEFINE_ENTRANCE(SCENE_KAKARIKO_VILLAGE, 0x10, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 65A */   [VANILLA_ENTRIES +  70] = DEFINE_ENTRANCE(SCENE_KAKARIKO_VILLAGE, 0x10, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 65B */   [VANILLA_ENTRIES +  71] = DEFINE_ENTRANCE(SCENE_KAKARIKO_VILLAGE, 0x10, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Hyrule Field near Market (exit table index 0x11)
/* 65C */   [VANILLA_ENTRIES +  72] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 65D */   [VANILLA_ENTRIES +  73] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 65E */   [VANILLA_ENTRIES +  74] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 65F */   [VANILLA_ENTRIES +  75] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

/* 660 */   [VANILLA_ENTRIES +  76] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x13, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 661 */   [VANILLA_ENTRIES +  77] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x13, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 662 */   [VANILLA_ENTRIES +  78] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x13, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 663 */   [VANILLA_ENTRIES +  79] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x13, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Hyrule Field Open (exit table index 0x12)
/* 664 */   [VANILLA_ENTRIES +  80] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 665 */   [VANILLA_ENTRIES +  81] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 666 */   [VANILLA_ENTRIES +  82] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 667 */   [VANILLA_ENTRIES +  83] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

/* 668 */   [VANILLA_ENTRIES +  84] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x14, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 669 */   [VANILLA_ENTRIES +  85] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x14, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 66A */   [VANILLA_ENTRIES +  86] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x14, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 66B */   [VANILLA_ENTRIES +  87] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x14, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Hyrule Field Southeast Boulder (exit table index 0x13)
/* 66C */   [VANILLA_ENTRIES +  88] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 66D */   [VANILLA_ENTRIES +  89] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 66E */   [VANILLA_ENTRIES +  90] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 66F */   [VANILLA_ENTRIES +  91] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

/* 670 */   [VANILLA_ENTRIES +  92] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x15, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 671 */   [VANILLA_ENTRIES +  93] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x15, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 672 */   [VANILLA_ENTRIES +  94] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x15, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 673 */   [VANILLA_ENTRIES +  95] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x15, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Lost Woods (exit table index 0x0A)
/* 674 */   [VANILLA_ENTRIES +  96] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 675 */   [VANILLA_ENTRIES +  97] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 676 */   [VANILLA_ENTRIES +  98] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 677 */   [VANILLA_ENTRIES +  99] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

/* 678 */   [VANILLA_ENTRIES + 100] = DEFINE_ENTRANCE(SCENE_LOST_WOODS, 0x0A, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 679 */   [VANILLA_ENTRIES + 101] = DEFINE_ENTRANCE(SCENE_LOST_WOODS, 0x0A, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 67A */   [VANILLA_ENTRIES + 102] = DEFINE_ENTRANCE(SCENE_LOST_WOODS, 0x0A, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 67B */   [VANILLA_ENTRIES + 103] = DEFINE_ENTRANCE(SCENE_LOST_WOODS, 0x0A, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Kokiri Forest (exit table index 0x0C)
            // Note that the last exit in the table for ENTR_DEKU_TREE_0 is NOT misinterpreted padding bytes.
            // One of the surface types references exit index 0x0B.
/* 67C */   [VANILLA_ENTRIES + 104] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 67D */   [VANILLA_ENTRIES + 105] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 67E */   [VANILLA_ENTRIES + 106] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 67F */   [VANILLA_ENTRIES + 107] = DEFINE_ENTRANCE(SCENE_GROTTOS, 0, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

            // Adult entrance lists includes the Deku Sprout cutscene entrance. Vanilla Child lists do not.
            // 0x0D child entrance assumes this is extended.
/* 680 */   [VANILLA_ENTRIES + 108] = DEFINE_ENTRANCE(SCENE_KOKIRI_FOREST, 0x0D, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 681 */   [VANILLA_ENTRIES + 109] = DEFINE_ENTRANCE(SCENE_KOKIRI_FOREST, 0x0D, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 682 */   [VANILLA_ENTRIES + 110] = DEFINE_ENTRANCE(SCENE_KOKIRI_FOREST, 0x0D, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 683 */   [VANILLA_ENTRIES + 111] = DEFINE_ENTRANCE(SCENE_KOKIRI_FOREST, 0x0D, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // ******************************************************************************************************************
            // 3 Scrub Grottos
            // ******************************************************************************************************************
            // Lake Hylia (exit table index 0x07)
            // Child entrance index assumes that the child layer has the Morpha blue warp entrance added
/* 684 */   [VANILLA_ENTRIES + 112] = DEFINE_ENTRANCE(SCENE_GROTTOS, 4, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 685 */   [VANILLA_ENTRIES + 113] = DEFINE_ENTRANCE(SCENE_GROTTOS, 4, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 686 */   [VANILLA_ENTRIES + 114] = DEFINE_ENTRANCE(SCENE_GROTTOS, 4, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 687 */   [VANILLA_ENTRIES + 115] = DEFINE_ENTRANCE(SCENE_GROTTOS, 4, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

/* 688 */   [VANILLA_ENTRIES + 116] = DEFINE_ENTRANCE(SCENE_LAKE_HYLIA, 0x0A, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 689 */   [VANILLA_ENTRIES + 117] = DEFINE_ENTRANCE(SCENE_LAKE_HYLIA, 0x0A, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 68A */   [VANILLA_ENTRIES + 118] = DEFINE_ENTRANCE(SCENE_LAKE_HYLIA, 0x0A, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 68B */   [VANILLA_ENTRIES + 119] = DEFINE_ENTRANCE(SCENE_LAKE_HYLIA, 0x0A, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Death Mountain Crater (exit table index 0x05)
/* 68C */   [VANILLA_ENTRIES + 120] = DEFINE_ENTRANCE(SCENE_GROTTOS, 4, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 68D */   [VANILLA_ENTRIES + 121] = DEFINE_ENTRANCE(SCENE_GROTTOS, 4, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 68E */   [VANILLA_ENTRIES + 122] = DEFINE_ENTRANCE(SCENE_GROTTOS, 4, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 68F */   [VANILLA_ENTRIES + 123] = DEFINE_ENTRANCE(SCENE_GROTTOS, 4, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

/* 690 */   [VANILLA_ENTRIES + 124] = DEFINE_ENTRANCE(SCENE_DEATH_MOUNTAIN_CRATER, 0x07, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 691 */   [VANILLA_ENTRIES + 125] = DEFINE_ENTRANCE(SCENE_DEATH_MOUNTAIN_CRATER, 0x07, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 692 */   [VANILLA_ENTRIES + 126] = DEFINE_ENTRANCE(SCENE_DEATH_MOUNTAIN_CRATER, 0x07, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 693 */   [VANILLA_ENTRIES + 127] = DEFINE_ENTRANCE(SCENE_DEATH_MOUNTAIN_CRATER, 0x07, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Goron City (exit table index 0x04)
/* 694 */   [VANILLA_ENTRIES + 128] = DEFINE_ENTRANCE(SCENE_GROTTOS, 4, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 695 */   [VANILLA_ENTRIES + 129] = DEFINE_ENTRANCE(SCENE_GROTTOS, 4, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 696 */   [VANILLA_ENTRIES + 130] = DEFINE_ENTRANCE(SCENE_GROTTOS, 4, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 697 */   [VANILLA_ENTRIES + 131] = DEFINE_ENTRANCE(SCENE_GROTTOS, 4, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

/* 698 */   [VANILLA_ENTRIES + 132] = DEFINE_ENTRANCE(SCENE_GORON_CITY, 0x04, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 699 */   [VANILLA_ENTRIES + 133] = DEFINE_ENTRANCE(SCENE_GORON_CITY, 0x04, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 69A */   [VANILLA_ENTRIES + 134] = DEFINE_ENTRANCE(SCENE_GORON_CITY, 0x04, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 69B */   [VANILLA_ENTRIES + 135] = DEFINE_ENTRANCE(SCENE_GORON_CITY, 0x04, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Lon Lon Ranch (exit table index 0x07)
/* 69C */   [VANILLA_ENTRIES + 136] = DEFINE_ENTRANCE(SCENE_GROTTOS, 4, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 69D */   [VANILLA_ENTRIES + 137] = DEFINE_ENTRANCE(SCENE_GROTTOS, 4, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 69E */   [VANILLA_ENTRIES + 138] = DEFINE_ENTRANCE(SCENE_GROTTOS, 4, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 69F */   [VANILLA_ENTRIES + 139] = DEFINE_ENTRANCE(SCENE_GROTTOS, 4, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

/* 6A0 */   [VANILLA_ENTRIES + 140] = DEFINE_ENTRANCE(SCENE_LON_LON_RANCH, 0x0B, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6A1 */   [VANILLA_ENTRIES + 141] = DEFINE_ENTRANCE(SCENE_LON_LON_RANCH, 0x0B, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6A2 */   [VANILLA_ENTRIES + 142] = DEFINE_ENTRANCE(SCENE_LON_LON_RANCH, 0x0B, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6A3 */   [VANILLA_ENTRIES + 143] = DEFINE_ENTRANCE(SCENE_LON_LON_RANCH, 0x0B, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // ******************************************************************************************************************
            // 2 Scrub Grottos
            // ******************************************************************************************************************
            // Desert Colossus (exit table index 0x05)
            // Child entrance index assumes that the child layer has the Twinrova blue warp entrance added
/* 6A4 */   [VANILLA_ENTRIES + 144] = DEFINE_ENTRANCE(SCENE_GROTTOS, 10, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 6A5 */   [VANILLA_ENTRIES + 145] = DEFINE_ENTRANCE(SCENE_GROTTOS, 10, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 6A6 */   [VANILLA_ENTRIES + 146] = DEFINE_ENTRANCE(SCENE_GROTTOS, 10, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 6A7 */   [VANILLA_ENTRIES + 147] = DEFINE_ENTRANCE(SCENE_GROTTOS, 10, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

/* 6A8 */   [VANILLA_ENTRIES + 148] = DEFINE_ENTRANCE(SCENE_DESERT_COLOSSUS, 0x09, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6A9 */   [VANILLA_ENTRIES + 149] = DEFINE_ENTRANCE(SCENE_DESERT_COLOSSUS, 0x09, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6AA */   [VANILLA_ENTRIES + 150] = DEFINE_ENTRANCE(SCENE_DESERT_COLOSSUS, 0x09, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6AB */   [VANILLA_ENTRIES + 151] = DEFINE_ENTRANCE(SCENE_DESERT_COLOSSUS, 0x09, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Zora River (exit table index 0x07)
/* 6AC */   [VANILLA_ENTRIES + 152] = DEFINE_ENTRANCE(SCENE_GROTTOS, 10, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 6AD */   [VANILLA_ENTRIES + 153] = DEFINE_ENTRANCE(SCENE_GROTTOS, 10, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 6AE */   [VANILLA_ENTRIES + 154] = DEFINE_ENTRANCE(SCENE_GROTTOS, 10, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 6AF */   [VANILLA_ENTRIES + 155] = DEFINE_ENTRANCE(SCENE_GROTTOS, 10, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

/* 6B0 */   [VANILLA_ENTRIES + 156] = DEFINE_ENTRANCE(SCENE_ZORAS_RIVER, 0x07, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6B1 */   [VANILLA_ENTRIES + 157] = DEFINE_ENTRANCE(SCENE_ZORAS_RIVER, 0x07, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6B2 */   [VANILLA_ENTRIES + 158] = DEFINE_ENTRANCE(SCENE_ZORAS_RIVER, 0x07, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6B3 */   [VANILLA_ENTRIES + 159] = DEFINE_ENTRANCE(SCENE_ZORAS_RIVER, 0x07, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Sacred Forest Meadow (exit table index 0x03)
/* 6B4 */   [VANILLA_ENTRIES + 160] = DEFINE_ENTRANCE(SCENE_GROTTOS, 10, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 6B5 */   [VANILLA_ENTRIES + 161] = DEFINE_ENTRANCE(SCENE_GROTTOS, 10, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 6B6 */   [VANILLA_ENTRIES + 162] = DEFINE_ENTRANCE(SCENE_GROTTOS, 10, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 6B7 */   [VANILLA_ENTRIES + 163] = DEFINE_ENTRANCE(SCENE_GROTTOS, 10, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

/* 6B8 */   [VANILLA_ENTRIES + 164] = DEFINE_ENTRANCE(SCENE_SACRED_FOREST_MEADOW, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6B9 */   [VANILLA_ENTRIES + 165] = DEFINE_ENTRANCE(SCENE_SACRED_FOREST_MEADOW, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6BA */   [VANILLA_ENTRIES + 166] = DEFINE_ENTRANCE(SCENE_SACRED_FOREST_MEADOW, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6BB */   [VANILLA_ENTRIES + 167] = DEFINE_ENTRANCE(SCENE_SACRED_FOREST_MEADOW, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Gerudo Valley (exit table index 0x05)
/* 6BC */   [VANILLA_ENTRIES + 168] = DEFINE_ENTRANCE(SCENE_GROTTOS, 10, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 6BD */   [VANILLA_ENTRIES + 169] = DEFINE_ENTRANCE(SCENE_GROTTOS, 10, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 6BE */   [VANILLA_ENTRIES + 170] = DEFINE_ENTRANCE(SCENE_GROTTOS, 10, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)
/* 6BF */   [VANILLA_ENTRIES + 171] = DEFINE_ENTRANCE(SCENE_GROTTOS, 10, false, true, TRANS_TYPE_FADE_BLACK, TRANS_TYPE_FADE_BLACK)

/* 6C0 */   [VANILLA_ENTRIES + 172] = DEFINE_ENTRANCE(SCENE_GERUDO_VALLEY, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6C1 */   [VANILLA_ENTRIES + 173] = DEFINE_ENTRANCE(SCENE_GERUDO_VALLEY, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6C2 */   [VANILLA_ENTRIES + 174] = DEFINE_ENTRANCE(SCENE_GERUDO_VALLEY, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6C3 */   [VANILLA_ENTRIES + 175] = DEFINE_ENTRANCE(SCENE_GERUDO_VALLEY, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // ******************************************************************************************************************
            // Return entrances for unique grottos
            // ******************************************************************************************************************
            // Death Mountain Trail Cow Grotto Exit (exit table index 0x07)
/* 6C4 */   [VANILLA_ENTRIES + 176] = DEFINE_ENTRANCE(SCENE_DEATH_MOUNTAIN_TRAIL, 0x07, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6C5 */   [VANILLA_ENTRIES + 177] = DEFINE_ENTRANCE(SCENE_DEATH_MOUNTAIN_TRAIL, 0x07, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6C6 */   [VANILLA_ENTRIES + 178] = DEFINE_ENTRANCE(SCENE_DEATH_MOUNTAIN_TRAIL, 0x07, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6C7 */   [VANILLA_ENTRIES + 179] = DEFINE_ENTRANCE(SCENE_DEATH_MOUNTAIN_TRAIL, 0x07, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Kakariko Village Redead Grotto Exit (exit table index 0x0F)
/* 6C8 */   [VANILLA_ENTRIES + 180] = DEFINE_ENTRANCE(SCENE_KAKARIKO_VILLAGE, 0x11, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6C9 */   [VANILLA_ENTRIES + 181] = DEFINE_ENTRANCE(SCENE_KAKARIKO_VILLAGE, 0x11, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6CA */   [VANILLA_ENTRIES + 182] = DEFINE_ENTRANCE(SCENE_KAKARIKO_VILLAGE, 0x11, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6CB */   [VANILLA_ENTRIES + 183] = DEFINE_ENTRANCE(SCENE_KAKARIKO_VILLAGE, 0x11, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Hyrule Castle Mud Wall Grotto Exit (exit table index 0x03)
/* 6CC */   [VANILLA_ENTRIES + 184] = DEFINE_ENTRANCE(SCENE_HYRULE_CASTLE, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6CD */   [VANILLA_ENTRIES + 185] = DEFINE_ENTRANCE(SCENE_HYRULE_CASTLE, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6CE */   [VANILLA_ENTRIES + 186] = DEFINE_ENTRANCE(SCENE_HYRULE_CASTLE, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6CF */   [VANILLA_ENTRIES + 187] = DEFINE_ENTRANCE(SCENE_HYRULE_CASTLE, 0x05, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Hyrule Field Tektite Grotto Exit (exit table index 0x14)
/* 6D0 */   [VANILLA_ENTRIES + 188] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x16, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6D1 */   [VANILLA_ENTRIES + 189] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x16, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6D2 */   [VANILLA_ENTRIES + 190] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x16, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6D3 */   [VANILLA_ENTRIES + 191] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x16, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Hyrule Field Big and Gold Skulltulas Grotto Exit (exit table index 0x15)
/* 6D4 */   [VANILLA_ENTRIES + 192] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x17, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6D5 */   [VANILLA_ENTRIES + 193] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x17, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6D6 */   [VANILLA_ENTRIES + 194] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x17, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6D7 */   [VANILLA_ENTRIES + 195] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x17, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Hyrule Field Webbed Cow Grotto Exit (exit table index 0x16)
/* 6D8 */   [VANILLA_ENTRIES + 196] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x18, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6D9 */   [VANILLA_ENTRIES + 197] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x18, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6DA */   [VANILLA_ENTRIES + 198] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x18, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6DB */   [VANILLA_ENTRIES + 199] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x18, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Hyrule Field 1 Scrub Grotto Exit (exit table index 0x17)
/* 6DC */   [VANILLA_ENTRIES + 200] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x19, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6DD */   [VANILLA_ENTRIES + 201] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x19, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6DE */   [VANILLA_ENTRIES + 202] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x19, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6DF */   [VANILLA_ENTRIES + 203] = DEFINE_ENTRANCE(SCENE_HYRULE_FIELD, 0x19, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Sacred Forest Meadow Wolfos Grotto Exit (exit table index 0x04)
/* 6E0 */   [VANILLA_ENTRIES + 204] = DEFINE_ENTRANCE(SCENE_SACRED_FOREST_MEADOW, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6E1 */   [VANILLA_ENTRIES + 205] = DEFINE_ENTRANCE(SCENE_SACRED_FOREST_MEADOW, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6E2 */   [VANILLA_ENTRIES + 206] = DEFINE_ENTRANCE(SCENE_SACRED_FOREST_MEADOW, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6E3 */   [VANILLA_ENTRIES + 207] = DEFINE_ENTRANCE(SCENE_SACRED_FOREST_MEADOW, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Lost Woods Upgrade Scrub Grotto Exit (exit table index 0x0B)
/* 6E4 */   [VANILLA_ENTRIES + 208] = DEFINE_ENTRANCE(SCENE_LOST_WOODS, 0x0B, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6E5 */   [VANILLA_ENTRIES + 209] = DEFINE_ENTRANCE(SCENE_LOST_WOODS, 0x0B, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6E6 */   [VANILLA_ENTRIES + 210] = DEFINE_ENTRANCE(SCENE_LOST_WOODS, 0x0B, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6E7 */   [VANILLA_ENTRIES + 211] = DEFINE_ENTRANCE(SCENE_LOST_WOODS, 0x0B, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Gerudo Valley Octorok Grotto Exit (exit table index 0x06)
/* 6E8 */   [VANILLA_ENTRIES + 212] = DEFINE_ENTRANCE(SCENE_GERUDO_VALLEY, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6E9 */   [VANILLA_ENTRIES + 213] = DEFINE_ENTRANCE(SCENE_GERUDO_VALLEY, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6EA */   [VANILLA_ENTRIES + 214] = DEFINE_ENTRANCE(SCENE_GERUDO_VALLEY, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6EB */   [VANILLA_ENTRIES + 215] = DEFINE_ENTRANCE(SCENE_GERUDO_VALLEY, 0x06, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)

            // Lost Woods Deku Theater Grotto Exit (exit table index 0x0C)
/* 6EC */   [VANILLA_ENTRIES + 216] = DEFINE_ENTRANCE(SCENE_LOST_WOODS, 0x0C, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6ED */   [VANILLA_ENTRIES + 217] = DEFINE_ENTRANCE(SCENE_LOST_WOODS, 0x0C, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6EE */   [VANILLA_ENTRIES + 218] = DEFINE_ENTRANCE(SCENE_LOST_WOODS, 0x0C, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
/* 6EF */   [VANILLA_ENTRIES + 219] = DEFINE_ENTRANCE(SCENE_LOST_WOODS, 0x0C, false, true, TRANS_TYPE_FADE_WHITE, TRANS_TYPE_FADE_WHITE)
};
