[mypy]
files = OoTRandomizer.py

# the types of settings cannot be determined in HintList, see https://mypy.readthedocs.io/en/stable/error_code_list.html#check-that-type-of-target-is-known-has-type
[mypy-HintList.*]
disable_error_code = has-type

#TODO also type check these modules
[mypy-Audiobank.*]
ignore_errors = True
[mypy-Goals.*]
ignore_errors = True
[mypy-Music.*]
ignore_errors = True
[mypy-MusicHelpers.*]
ignore_errors = True
[mypy-Plandomizer.*]
ignore_errors = True
[mypy-RuleParser.*]
ignore_errors = True
[mypy-Spoiler.*]
ignore_errors = True
