[mypy]
files = OoTRandomizer.py

#TODO also type check these modules
[mypy-Goals.*]
ignore_errors = True
[mypy-Plandomizer.*]
ignore_errors = True
[mypy-RuleParser.*]
ignore_errors = True
[mypy-Spoiler.*]
ignore_errors = True
