from version import __version__
from collections import OrderedDict
from Item import Item
from Hints import gossipLocations
import re
import random
import json

HASH_ICONS = [
    'Deku Stick',
    'Deku Nut',
    'Bow',
    'Slingshot',
    'Fairy Ocarina',
    'Bombchu',
    'Longshot',
    'Boomerang',
    'Lens of Truth',
    'Beans',
    'Megaton Hammer',
    'Bottled Fish',
    'Bottled Milk',
    'Mask of Truth',
    'SOLD OUT',
    'Cucco',
    'Mushroom',
    'Saw',
    'Frog',
    'Master Sword',
    'Mirror Shield',
    'Kokiri Tunic',
    'Hover Boots',
    'Silver Gauntlets',
    'Gold Scale',
    'Stone of Agony',
    'Skull Token',
    'Heart Container',
    'Boss Key',
    'Compass',
    'Map',
    'Big Magic',
]

sort_locations = [
    # Abbreviations
    #   DMC     Death Mountain Crater
    #   DMT     Death Mountain Trail
    #   GC      Goron City
    #   GF      Gerudo Fortress
    #   GS      Gold Skulltula
    #   GV      Gerudo Valley
    #   HC      Hyrule Castle
    #   HF      Hyrule Field
    #   KF      Kokiri Forest
    #   LH      Lake Hylia
    #   LLR     Lon Lon Ranch
    #   LW      Lost Woods
    #   OGC     Outside Ganon's Castle
    #   SFM     Sacred Forest Meadow
    #   ToT     Temple of Time
    #   ZD      Zora's Domain
    #   ZF      Zora's Fountain
    #   ZR      Zora's River
    
    # Dungeon rewards
    "Links Pocket",
    "Queen Gohma",
    "King Dodongo",
    "Barinade",
    "Phantom Ganon",
    "Volvagia",
    "Morpha",
    "Twinrova",
    "Bongo Bongo",
    "Ganon",

    # Songs
    "Song from Impa",
    "Song from Malon",
    "Song from Saria",
    "Song from Composers Grave",
    "Song from Ocarina of Time",
    "Song from Windmill",
    "Sheik in Forest",
    "Sheik in Crater",
    "Sheik in Ice Cavern",
    "Sheik at Colossus",
    "Sheik in Kakariko",
    "Sheik at Temple",

    # Overworld
    "KF Midos Top Left Chest",
    "KF Midos Top Right Chest",
    "KF Midos Bottom Left Chest",
    "KF Midos Bottom Right Chest",
    "KF Kokiri Sword Chest",
    "KF Storms Grotto Chest",
    "KF Links House Cow",
    "KF GS Know It All House",
    "KF GS Bean Patch",
    "KF GS House of Twins",
    "KF Shop Item 1",
    "KF Shop Item 2",
    "KF Shop Item 3",
    "KF Shop Item 4",
    "KF Shop Item 5",
    "KF Shop Item 6",
    "KF Shop Item 7",
    "KF Shop Item 8",

    "LW Gift from Saria",
    "LW Ocarina Memory Game",
    "LW Target in Woods",
    "LW Near Shortcuts Grotto Chest",
    "Deku Theater Skull Mask",
    "Deku Theater Mask of Truth",
    "LW Skull Kid",
    "LW Deku Scrub Near Bridge",
    "LW Deku Scrub Near Deku Theater Left",
    "LW Deku Scrub Near Deku Theater Right",
    "LW Deku Scrub Grotto Front",
    "LW Deku Scrub Grotto Rear",
    "LW GS Bean Patch Near Bridge",
    "LW GS Bean Patch Near Theater",
    "LW GS Above Theater",

    "SFM Wolfos Grotto Chest",
    "SFM Deku Scrub Grotto Front",
    "SFM Deku Scrub Grotto Rear",
    "SFM GS",

    "HF Ocarina of Time Item",
    "HF Near Market Grotto Chest",
    "HF Tektite Grotto Freestanding PoH",
    "HF Southeast Grotto Chest",
    "HF Open Grotto Chest",
    "HF Deku Scrub Grotto",
    "HF Cow Grotto Cow",
    "HF GS Cow Grotto",
    "HF GS Near Kak Grotto",

    "Market Shooting Gallery Reward",
    "Market Bombchu Bowling First Prize",
    "Market Bombchu Bowling Second Prize",
    "Market Bombchu Bowling Bombchus",
    "Market Lost Dog",
    "Market Treasure Chest Game Reward",
    "Market 10 Big Poes",
    "Market GS Guard House",
    "Market Bazaar Item 1",
    "Market Bazaar Item 2",
    "Market Bazaar Item 3",
    "Market Bazaar Item 4",
    "Market Bazaar Item 5",
    "Market Bazaar Item 6",
    "Market Bazaar Item 7",
    "Market Bazaar Item 8",
    "Market Potion Shop Item 1",
    "Market Potion Shop Item 2",
    "Market Potion Shop Item 3",
    "Market Potion Shop Item 4",
    "Market Potion Shop Item 5",
    "Market Potion Shop Item 6",
    "Market Potion Shop Item 7",
    "Market Potion Shop Item 8",
    "Market Bombchu Shop Item 1",
    "Market Bombchu Shop Item 2",
    "Market Bombchu Shop Item 3",
    "Market Bombchu Shop Item 4",
    "Market Bombchu Shop Item 5",
    "Market Bombchu Shop Item 6",
    "Market Bombchu Shop Item 7",
    "Market Bombchu Shop Item 8",

    "ToT Light Arrows Cutscene",

    "HC Malon Egg",
    "HC Zeldas Letter",
    "HC Great Fairy Reward",
    "HC GS Tree",
    "HC GS Storms Grotto",

    "LLR Talons Chickens",
    "LLR Freestanding PoH",
    "LLR Deku Scrub Grotto Left",
    "LLR Deku Scrub Grotto Center",
    "LLR Deku Scrub Grotto Right",
    "LLR Stables Left Cow",
    "LLR Stables Right Cow",
    "LLR Tower Left Cow",
    "LLR Tower Right Cow",
    "LLR GS House Window",
    "LLR GS Tree",
    "LLR GS Rain Shed",
    "LLR GS Back Wall",

    "Kak Anju as Child",
    "Kak Anju as Adult",
    "Kak Impas House Freestanding PoH",
    "Kak Windmill Freestanding PoH",
    "Kak Man on Roof",
    "Kak Open Grotto Chest",
    "Kak Redead Grotto Chest",
    "Kak Shooting Gallery Reward",
    "Kak 10 Gold Skulltula Reward",
    "Kak 20 Gold Skulltula Reward",
    "Kak 30 Gold Skulltula Reward",
    "Kak 40 Gold Skulltula Reward",
    "Kak 50 Gold Skulltula Reward",
    "Kak Impas House Cow",
    "Kak GS Tree",
    "Kak GS Guards House",
    "Kak GS Watchtower",
    "Kak GS Skulltula House",
    "Kak GS House Under Construction",
    "Kak GS Above Impas House",
    "Kak Bazaar Item 1",
    "Kak Bazaar Item 2",
    "Kak Bazaar Item 3",
    "Kak Bazaar Item 4",
    "Kak Bazaar Item 5",
    "Kak Bazaar Item 6",
    "Kak Bazaar Item 7",
    "Kak Bazaar Item 8",
    "Kak Potion Shop Item 1",
    "Kak Potion Shop Item 2",
    "Kak Potion Shop Item 3",
    "Kak Potion Shop Item 4",
    "Kak Potion Shop Item 5",
    "Kak Potion Shop Item 6",
    "Kak Potion Shop Item 7",
    "Kak Potion Shop Item 8",

    "Graveyard Shield Grave Chest",
    "Graveyard Heart Piece Grave Chest",
    "Graveyard Composers Grave Chest",
    "Graveyard Freestanding PoH",
    "Graveyard Dampe Gravedigging Tour",
    "Graveyard Hookshot Chest",
    "Graveyard Dampe Race Freestanding PoH",
    "Graveyard GS Bean Patch",
    "Graveyard GS Wall",

    "DMT Freestanding PoH",
    "DMT Chest",
    "DMT Storms Grotto Chest",
    "DMT Great Fairy Reward",
    "DMT Biggoron",
    "DMT Cow Grotto Cow",
    "DMT GS Near Kak",
    "DMT GS Bean Patch",
    "DMT GS Above Dodongos Cavern",
    "DMT GS Falling Rocks Path",

    "GC Darunias Joy",
    "GC Pot Freestanding PoH",
    "GC Rolling Goron as Child",
    "GC Rolling Goron as Adult",
    "GC Medigoron",
    "GC Maze Left Chest",
    "GC Maze Right Chest",
    "GC Maze Center Chest",
    "GC Deku Scrub Grotto Left",
    "GC Deku Scrub Grotto Center",
    "GC Deku Scrub Grotto Right",
    "GC GS Boulder Maze", 
    "GC GS Center Platform",
    "GC Shop Item 1",
    "GC Shop Item 2",
    "GC Shop Item 3",
    "GC Shop Item 4",
    "GC Shop Item 5",
    "GC Shop Item 6",
    "GC Shop Item 7",
    "GC Shop Item 8",

    "DMC Volcano Freestanding PoH",
    "DMC Wall Freestanding PoH",
    "DMC Upper Grotto Chest",
    "DMC Great Fairy Reward",
    "DMC Deku Scrub",
    "DMC Deku Scrub Grotto Left",
    "DMC Deku Scrub Grotto Center",
    "DMC Deku Scrub Grotto Right",
    "DMC GS Crate",
    "DMC GS Bean Patch",

    "ZR Magic Bean Salesman",
    "ZR Open Grotto Chest",
    "ZR Frogs in the Rain",
    "ZR Frogs Ocarina Game",
    "ZR Near Open Grotto Freestanding PoH",
    "ZR Near Domain Freestanding PoH",
    "ZR Deku Scrub Grotto Front",
    "ZR Deku Scrub Grotto Rear",
    "ZR GS Tree",
    "ZR GS Ladder",
    "ZR GS Near Raised Grottos",
    "ZR GS Above Bridge",

    "ZD Diving Minigame",
    "ZD Chest",
    "ZD King Zora Thawed",
    "ZD GS Frozen Waterfall",
    "ZD Shop Item 1",
    "ZD Shop Item 2",
    "ZD Shop Item 3",
    "ZD Shop Item 4",
    "ZD Shop Item 5",
    "ZD Shop Item 6",
    "ZD Shop Item 7",
    "ZD Shop Item 8",

    "ZF Great Fairy Reward",
    "ZF Iceberg Freestanding PoH",
    "ZF Bottom Freestanding PoH",
    "ZF GS Above the Log",
    "ZF GS Tree",
    "ZF GS Hidden Cave",
   
    "LH Underwater Item",
    "LH Child Fishing",
    "LH Adult Fishing",
    "LH Lab Dive",
    "LH Freestanding PoH",
    "LH Sun",
    "LH Deku Scrub Grotto Left",
    "LH Deku Scrub Grotto Center",
    "LH Deku Scrub Grotto Right",
    "LH GS Bean Patch",
    "LH GS Lab Wall",
    "LH GS Small Island",
    "LH GS Lab Crate",
    "LH GS Tree",

    "GV Crate Freestanding PoH",
    "GV Waterfall Freestanding PoH",
    "GV Chest",
    "GV Deku Scrub Grotto Front",
    "GV Deku Scrub Grotto Rear",
    "GV Cow",
    "GV GS Small Bridge",
    "GV GS Bean Patch",
    "GV GS Behind Tent",
    "GV GS Pillar",

    "GF North F1 Carpenter",
    "GF North F2 Carpenter",
    "GF South F1 Carpenter",
    "GF South F2 Carpenter",
    "GF Gerudo Membership Card",
    "GF Chest",
    "GF HBA 1000 Points",
    "GF HBA 1500 Points",
    "GF GS Top Floor",
    "GF GS Archery Range",

    "Wasteland Chest",
    "Wasteland Bombchu Salesman",
    "Wasteland GS",

    "Colossus Great Fairy Reward",
    "Colossus Freestanding PoH",
    "Colossus Deku Scrub Grotto Front",
    "Colossus Deku Scrub Grotto Rear",
    "Colossus GS Bean Patch",
    "Colossus GS Tree",
    "Colossus GS Hill",

    "OGC Great Fairy Reward",
    "OGC GS",

    # Dungeons
    "Deku Tree Map Chest",
    "Deku Tree Slingshot Room Side Chest",
    "Deku Tree Slingshot Chest",
    "Deku Tree Compass Chest",
    "Deku Tree Compass Room Side Chest",
    "Deku Tree Basement Chest",
    "Deku Tree GS Compass Room",
    "Deku Tree GS Basement Vines",
    "Deku Tree GS Basement Gate",
    "Deku Tree GS Basement Back Room",

    "Deku Tree MQ Map Chest",
    "Deku Tree MQ Slingshot Chest",
    "Deku Tree MQ Slingshot Room Back Chest",
    "Deku Tree MQ Compass Chest",
    "Deku Tree MQ Basement Chest",
    "Deku Tree MQ Before Spinning Log Chest",
    "Deku Tree MQ After Spinning Log Chest",
    "Deku Tree MQ Deku Scrub",
    "Deku Tree MQ GS Lobby",
    "Deku Tree MQ GS Compass Room",
    "Deku Tree MQ GS Basement Graves Room",
    "Deku Tree MQ GS Basement Back Room",
 
    "Deku Tree Queen Gohma Heart",

    "Dodongos Cavern Map Chest",
    "Dodongos Cavern Compass Chest",
    "Dodongos Cavern Bomb Flower Platform Chest",
    "Dodongos Cavern Bomb Bag Chest",
    "Dodongos Cavern End of Bridge Chest",
    "Dodongos Cavern Deku Scrub Side Room Near Dodongos",
    "Dodongos Cavern Deku Scrub Lobby",
    "Dodongos Cavern Deku Scrub Near Bomb Bag Left",
    "Dodongos Cavern Deku Scrub Near Bomb Bag Right",
    "Dodongos Cavern GS Side Room Near Lower Lizalfos",
    "Dodongos Cavern GS Scarecrow",
    "Dodongos Cavern GS Alcove Above Stairs",
    "Dodongos Cavern GS Vines Above Stairs",
    "Dodongos Cavern GS Back Room",

    "Dodongos Cavern MQ Map Chest",
    "Dodongos Cavern MQ Bomb Bag Chest",
    "Dodongos Cavern MQ Torch Puzzle Room Chest",
    "Dodongos Cavern MQ Larvae Room Chest",
    "Dodongos Cavern MQ Compass Chest",
    "Dodongos Cavern MQ Under Grave Chest",
    "Dodongos Cavern MQ Deku Scrub Lobby Front",
    "Dodongos Cavern MQ Deku Scrub Lobby Rear",
    "Dodongos Cavern MQ Deku Scrub Side Room Near Lower Lizalfos",
    "Dodongos Cavern MQ Deku Scrub Staircase",
    "Dodongos Cavern MQ GS Scrub Room",
    "Dodongos Cavern MQ GS Larvae Room",
    "Dodongos Cavern MQ GS Lizalfos Room",
    "Dodongos Cavern MQ GS Song of Time Block Room",
    "Dodongos Cavern MQ GS Back Area",
    
    "Dodongos Cavern Boss Room Chest",
    "Dodongos Cavern King Dodongo Heart",

    "Jabu Jabus Belly Boomerang Chest",
    "Jabu Jabus Belly Map Chest",
    "Jabu Jabus Belly Compass Chest",
    "Jabu Jabus Belly Deku Scrub",
    "Jabu Jabus Belly GS Water Switch Room",
    "Jabu Jabus Belly GS Lobby Basement Lower",
    "Jabu Jabus Belly GS Lobby Basement Upper",
    "Jabu Jabus Belly GS Near Boss",

    "Jabu Jabus Belly MQ Map Chest",
    "Jabu Jabus Belly MQ First Room Side Chest",
    "Jabu Jabus Belly MQ Second Room Lower Chest",
    "Jabu Jabus Belly MQ Compass Chest",
    "Jabu Jabus Belly MQ Basement Near Switches Chest",
    "Jabu Jabus Belly MQ Basement Near Vines Chest",
    "Jabu Jabus Belly MQ Boomerang Room Small Chest",
    "Jabu Jabus Belly MQ Boomerang Chest",
    "Jabu Jabus Belly MQ Falling Like Like Room Chest",
    "Jabu Jabus Belly MQ Second Room Upper Chest",
    "Jabu Jabus Belly MQ Near Boss Chest",
    "Jabu Jabus Belly MQ Cow",
    "Jabu Jabus Belly MQ GS Boomerang Chest Room",
    "Jabu Jabus Belly MQ GS Tailpasaran Room",
    "Jabu Jabus Belly MQ GS Invisible Enemies Room",
    "Jabu Jabus Belly MQ GS Near Boss",

    "Jabu Jabus Belly Barinade Heart",

    "Bottom of the Well Front Left Fake Wall Chest",
    "Bottom of the Well Front Center Bombable Chest",
    "Bottom of the Well Back Left Bombable Chest",
    "Bottom of the Well Underwater Left Chest",
    "Bottom of the Well Freestanding Key",
    "Bottom of the Well Compass Chest",
    "Bottom of the Well Center Skulltula Chest",
    "Bottom of the Well Right Bottom Fake Wall Chest",
    "Bottom of the Well Fire Keese Chest",
    "Bottom of the Well Like Like Chest",
    "Bottom of the Well Map Chest",
    "Bottom of the Well Underwater Front Chest",
    "Bottom of the Well Invisible Chest",
    "Bottom of the Well Lens of Truth Chest",
    "Bottom of the Well GS West Inner Room",
    "Bottom of the Well GS East Inner Room",
    "Bottom of the Well GS Like Like Cage",

    "Bottom of the Well MQ Map Chest",
    "Bottom of the Well MQ East Inner Room Freestanding Key",
    "Bottom of the Well MQ Compass Chest",
    "Bottom of the Well MQ Dead Hand Freestanding Key",
    "Bottom of the Well MQ Lens of Truth Chest",
    "Bottom of the Well MQ GS Coffin Room",
    "Bottom of the Well MQ GS West Inner Room",
    "Bottom of the Well MQ GS Basement",

    "Forest Temple First Room Chest",
    "Forest Temple First Stalfos Chest",
    "Forest Temple Raised Island Courtyard Chest",
    "Forest Temple Map Chest",
    "Forest Temple Well Chest",
    "Forest Temple Eye Switch Chest",
    "Forest Temple Boss Key Chest",
    "Forest Temple Floormaster Chest",
    "Forest Temple Red Poe Chest",
    "Forest Temple Bow Chest",
    "Forest Temple Blue Poe Chest",
    "Forest Temple Falling Ceiling Room Chest",
    "Forest Temple Basement Chest",
    "Forest Temple GS First Room",
    "Forest Temple GS Lobby",
    "Forest Temple GS Raised Island Courtyard",
    "Forest Temple GS Level Island Courtyard",
    "Forest Temple GS Basement",

    "Forest Temple MQ First Room Chest",
    "Forest Temple MQ Wolfos Chest",
    "Forest Temple MQ Well Chest",
    "Forest Temple MQ Raised Island Courtyard Lower Chest",
    "Forest Temple MQ Raised Island Courtyard Upper Chest",
    "Forest Temple MQ Boss Key Chest",
    "Forest Temple MQ Redead Chest",
    "Forest Temple MQ Map Chest",
    "Forest Temple MQ Bow Chest",
    "Forest Temple MQ Compass Chest",
    "Forest Temple MQ Falling Ceiling Room Chest",
    "Forest Temple MQ Basement Chest",
    "Forest Temple MQ GS First Hallway",
    "Forest Temple MQ GS Raised Island Courtyard",
    "Forest Temple MQ GS Level Island Courtyard",
    "Forest Temple MQ GS Well",
    "Forest Temple MQ GS Block Push Room",

    "Forest Temple Phantom Ganon Heart",

    "Fire Temple Near Boss Chest",
    "Fire Temple Flare Dancer Chest",
    "Fire Temple Boss Key Chest",
    "Fire Temple Big Lava Room Lower Open Door Chest",
    "Fire Temple Big Lava Room Blocked Door Chest",
    "Fire Temple Boulder Maze Lower Chest",
    "Fire Temple Boulder Maze Side Room Chest",
    "Fire Temple Map Chest",
    "Fire Temple Boulder Maze Shortcut Chest",
    "Fire Temple Boulder Maze Upper Chest",
    "Fire Temple Scarecrow Chest",
    "Fire Temple Compass Chest",
    "Fire Temple Megaton Hammer Chest",
    "Fire Temple Highest Goron Chest",
    "Fire Temple GS Boss Key Loop",
    "Fire Temple GS Song of Time Room",
    "Fire Temple GS Boulder Maze",
    "Fire Temple GS Scarecrow Climb",
    "Fire Temple GS Scarecrow Top",

    "Fire Temple MQ Map Room Side Chest",
    "Fire Temple MQ Megaton Hammer Chest",
    "Fire Temple MQ Map Chest",
    "Fire Temple MQ Near Boss Chest",
    "Fire Temple MQ Big Lava Room Blocked Door Chest",
    "Fire Temple MQ Boss Key Chest",
    "Fire Temple MQ Lizalfos Maze Side Room Chest",
    "Fire Temple MQ Compass Chest",
    "Fire Temple MQ Lizalfos Maze Upper Chest",
    "Fire Temple MQ Lizalfos Maze Lower Chest",
    "Fire Temple MQ Freestanding Key",
    "Fire Temple MQ Chest On Fire",
    "Fire Temple MQ GS Big Lava Room Open Door",
    "Fire Temple MQ GS Skull On Fire",
    "Fire Temple MQ GS Fire Wall Maze Center",
    "Fire Temple MQ GS Fire Wall Maze Side Room",
    "Fire Temple MQ GS Above Fire Wall Maze",

    "Fire Temple Volvagia Heart",

    "Water Temple Compass Chest",
    "Water Temple Map Chest",
    "Water Temple Cracked Wall Chest",
    "Water Temple Torches Chest",
    "Water Temple Boss Key Chest",
    "Water Temple Central Pillar Chest",
    "Water Temple Central Bow Target Chest",
    "Water Temple Longshot Chest",
    "Water Temple River Chest",
    "Water Temple Dragon Chest",
    "Water Temple GS Behind Gate",
    "Water Temple GS Near Boss Key Chest",
    "Water Temple GS Central Pillar",
    "Water Temple GS Falling Platform Room",
    "Water Temple GS River",

    "Water Temple MQ Longshot Chest",
    "Water Temple MQ Map Chest",
    "Water Temple MQ Compass Chest",
    "Water Temple MQ Central Pillar Chest",
    "Water Temple MQ Boss Key Chest",
    "Water Temple MQ Freestanding Key",
    "Water Temple MQ GS Lizalfos Hallway",
    "Water Temple MQ GS Before Upper Water Switch",
    "Water Temple MQ GS River",
    "Water Temple MQ GS Freestanding Key Area",
    "Water Temple MQ GS Triple Wall Torch",

    "Water Temple Morpha Heart",

    "Shadow Temple Map Chest",
    "Shadow Temple Hover Boots Chest",
    "Shadow Temple Compass Chest",
    "Shadow Temple Early Silver Rupee Chest",
    "Shadow Temple Invisible Blades Visible Chest",
    "Shadow Temple Invisible Blades Invisible Chest",
    "Shadow Temple Falling Spikes Lower Chest",
    "Shadow Temple Falling Spikes Upper Chest",
    "Shadow Temple Falling Spikes Switch Chest",
    "Shadow Temple Invisible Spikes Chest",
    "Shadow Temple Freestanding Key",
    "Shadow Temple Wind Hint Chest",
    "Shadow Temple After Wind Enemy Chest",
    "Shadow Temple After Wind Hidden Chest",
    "Shadow Temple Spike Walls Left Chest",
    "Shadow Temple Boss Key Chest",
    "Shadow Temple Invisible Floormaster Chest",
    "Shadow Temple GS Like Like Room",
    "Shadow Temple GS Falling Spikes Room",
    "Shadow Temple GS Single Giant Pot",
    "Shadow Temple GS Near Ship",
    "Shadow Temple GS Triple Giant Pot",

    "Shadow Temple MQ Early Gibdos Chest",
    "Shadow Temple MQ Map Chest",
    "Shadow Temple MQ Near Ship Invisible Chest",
    "Shadow Temple MQ Compass Chest",
    "Shadow Temple MQ Hover Boots Chest",
    "Shadow Temple MQ Invisible Blades Invisible Chest",
    "Shadow Temple MQ Invisible Blades Visible Chest",
    "Shadow Temple MQ Beamos Silver Rupees Chest",
    "Shadow Temple MQ Falling Spikes Lower Chest",
    "Shadow Temple MQ Falling Spikes Upper Chest",
    "Shadow Temple MQ Falling Spikes Switch Chest",
    "Shadow Temple MQ Invisible Spikes Chest",
    "Shadow Temple MQ Stalfos Room Chest",
    "Shadow Temple MQ Wind Hint Chest",
    "Shadow Temple MQ After Wind Hidden Chest",
    "Shadow Temple MQ After Wind Enemy Chest",
    "Shadow Temple MQ Boss Key Chest",
    "Shadow Temple MQ Spike Walls Left Chest",
    "Shadow Temple MQ Freestanding Key",
    "Shadow Temple MQ Bomb Flower Chest",
    "Shadow Temple MQ GS Falling Spikes Room",
    "Shadow Temple MQ GS Wind Hint Room",
    "Shadow Temple MQ GS After Wind",
    "Shadow Temple MQ GS After Ship",
    "Shadow Temple MQ GS Near Boss",

    "Shadow Temple Bongo Bongo Heart",

    # Vanilla and MQ locations are mixed to ensure the position of "Silver Gauntlets/Mirror Shield Chests" are correct for both versions of Spirit Temple.
    "Spirit Temple Child Bridge Chest",
    "Spirit Temple Child Early Torches Chest",
    "Spirit Temple Child Climb North Chest",
    "Spirit Temple Child Climb East Chest",
    "Spirit Temple Map Chest",
    "Spirit Temple Sun Block Room Chest",
    "Spirit Temple MQ Entrance Front Left Chest",
    "Spirit Temple MQ Entrance Back Left Chest",
    "Spirit Temple MQ Entrance Back Right Chest",
    "Spirit Temple MQ Entrance Front Right Chest",
    "Spirit Temple MQ Map Chest",
    "Spirit Temple MQ Map Room Enemy Chest",
    "Spirit Temple MQ Child Climb North Chest",
    "Spirit Temple MQ Child Climb South Chest",
    "Spirit Temple MQ Compass Chest",
    "Spirit Temple MQ Silver Block Hallway Chest",
    "Spirit Temple MQ Sun Block Room Chest",
    "Spirit Temple Silver Gauntlets Chest",
    "Spirit Temple Compass Chest",
    "Spirit Temple Early Adult Right Chest",
    "Spirit Temple First Mirror Left Chest",
    "Spirit Temple First Mirror Right Chest",
    "Spirit Temple Statue Room Northeast Chest",
    "Spirit Temple Statue Room Hand Chest",
    "Spirit Temple Near Four Armos Chest",
    "Spirit Temple Hallway Right Invisible Chest",
    "Spirit Temple Hallway Left Invisible Chest",
    "Spirit Temple MQ Child Hammer Switch Chest",
    "Spirit Temple MQ Statue Room Lullaby Chest",
    "Spirit Temple MQ Statue Room Invisible Chest",
    "Spirit Temple MQ Leever Room Chest",
    "Spirit Temple MQ Symphony Room Chest",
    "Spirit Temple MQ Beamos Room Chest",
    "Spirit Temple MQ Chest Switch Chest",
    "Spirit Temple MQ Boss Key Chest",
    "Spirit Temple Mirror Shield Chest",
    "Spirit Temple Boss Key Chest",
    "Spirit Temple Topmost Chest",
    "Spirit Temple GS Metal Fence",
    "Spirit Temple GS Sun on Floor Room",
    "Spirit Temple GS Hall After Sun Block Room",
    "Spirit Temple GS Lobby",
    "Spirit Temple GS Boulder Room",
    "Spirit Temple MQ Mirror Puzzle Invisible Chest",
    "Spirit Temple MQ GS Sun Block Room",
    "Spirit Temple MQ GS Leever Room",
    "Spirit Temple MQ GS Symphony Room",
    "Spirit Temple MQ GS Nine Thrones Room West",
    "Spirit Temple MQ GS Nine Thrones Room North",

    "Spirit Temple Twinrova Heart",

    "Ice Cavern Map Chest",
    "Ice Cavern Compass Chest",
    "Ice Cavern Freestanding PoH",
    "Ice Cavern Iron Boots Chest",
    "Ice Cavern GS Spinning Scythe Room",
    "Ice Cavern GS Heart Piece Room",
    "Ice Cavern GS Push Block Room",

    "Ice Cavern MQ Map Chest",
    "Ice Cavern MQ Compass Chest",
    "Ice Cavern MQ Freestanding PoH",
    "Ice Cavern MQ Iron Boots Chest",
    "Ice Cavern MQ GS Red Ice",
    "Ice Cavern MQ GS Ice Block",
    "Ice Cavern MQ GS Scarecrow",

    "Gerudo Training Grounds Lobby Left Chest",
    "Gerudo Training Grounds Lobby Right Chest",
    "Gerudo Training Grounds Stalfos Chest",
    "Gerudo Training Grounds Before Heavy Block Chest",
    "Gerudo Training Grounds Heavy Block First Chest",
    "Gerudo Training Grounds Heavy Block Second Chest",
    "Gerudo Training Grounds Heavy Block Third Chest",
    "Gerudo Training Grounds Heavy Block Fourth Chest",
    "Gerudo Training Grounds Eye Statue Chest",
    "Gerudo Training Grounds Near Scarecrow Chest",
    "Gerudo Training Grounds Hammer Room Clear Chest",
    "Gerudo Training Grounds Hammer Room Switch Chest",
    "Gerudo Training Grounds Freestanding Key",
    "Gerudo Training Grounds Maze Right Central Chest",
    "Gerudo Training Grounds Maze Right Side Chest",
    "Gerudo Training Grounds Underwater Silver Rupee Chest",
    "Gerudo Training Grounds Beamos Chest",
    "Gerudo Training Grounds Hidden Ceiling Chest",
    "Gerudo Training Grounds Maze Path First Chest",
    "Gerudo Training Grounds Maze Path Second Chest",
    "Gerudo Training Grounds Maze Path Third Chest",
    "Gerudo Training Grounds Maze Path Final Chest",

    "Gerudo Training Grounds MQ Lobby Left Chest",
    "Gerudo Training Grounds MQ Lobby Right Chest",
    "Gerudo Training Grounds MQ First Iron Knuckle Chest",
    "Gerudo Training Grounds MQ Before Heavy Block Chest",
    "Gerudo Training Grounds MQ Heavy Block Chest",
    "Gerudo Training Grounds MQ Eye Statue Chest",
    "Gerudo Training Grounds MQ Ice Arrows Chest",
    "Gerudo Training Grounds MQ Second Iron Knuckle Chest",
    "Gerudo Training Grounds MQ Flame Circle Chest",
    "Gerudo Training Grounds MQ Maze Right Central Chest",
    "Gerudo Training Grounds MQ Maze Right Side Chest",
    "Gerudo Training Grounds MQ Underwater Silver Rupee Chest",
    "Gerudo Training Grounds MQ Dinolfos Chest",
    "Gerudo Training Grounds MQ Hidden Ceiling Chest",
    "Gerudo Training Grounds MQ Maze Path First Chest",
    "Gerudo Training Grounds MQ Maze Path Second Chest",
    "Gerudo Training Grounds MQ Maze Path Third Chest",

    "Ganons Castle Forest Trial Chest",
    "Ganons Castle Water Trial Left Chest",
    "Ganons Castle Water Trial Right Chest",
    "Ganons Castle Shadow Trial Front Chest",
    "Ganons Castle Shadow Trial Golden Gauntlets Chest",
    "Ganons Castle Light Trial First Left Chest",
    "Ganons Castle Light Trial Second Left Chest",
    "Ganons Castle Light Trial Third Left Chest",
    "Ganons Castle Light Trial First Right Chest",
    "Ganons Castle Light Trial Second Right Chest",
    "Ganons Castle Light Trial Third Right Chest",
    "Ganons Castle Light Trial Invisible Enemies Chest",
    "Ganons Castle Light Trial Lullaby Chest",
    "Ganons Castle Spirit Trial Crystal Switch Chest",
    "Ganons Castle Spirit Trial Invisible Chest",
    "Ganons Castle Deku Scrub Left",
    "Ganons Castle Deku Scrub Center-Left",
    "Ganons Castle Deku Scrub Center-Right",
    "Ganons Castle Deku Scrub Right",

    "Ganons Castle MQ Forest Trial Freestanding Key",
    "Ganons Castle MQ Forest Trial Eye Switch Chest",
    "Ganons Castle MQ Forest Trial Frozen Eye Switch Chest",
    "Ganons Castle MQ Water Trial Chest",
    "Ganons Castle MQ Shadow Trial Bomb Flower Chest",
    "Ganons Castle MQ Shadow Trial Eye Switch Chest",
    "Ganons Castle MQ Light Trial Lullaby Chest",
    "Ganons Castle MQ Spirit Trial First Chest",
    "Ganons Castle MQ Spirit Trial Invisible Chest",
    "Ganons Castle MQ Spirit Trial Sun Front Left Chest",
    "Ganons Castle MQ Spirit Trial Sun Back Left Chest",
    "Ganons Castle MQ Spirit Trial Sun Back Right Chest",
    "Ganons Castle MQ Spirit Trial Golden Gauntlets Chest",
    "Ganons Castle MQ Deku Scrub Left",
    "Ganons Castle MQ Deku Scrub Center-Left",
    "Ganons Castle MQ Deku Scrub Center",
    "Ganons Castle MQ Deku Scrub Center-Right",
    "Ganons Castle MQ Deku Scrub Right",

    "Ganons Tower Boss Key Chest"
]


class Spoiler(object):

    def __init__(self, worlds):
        self.worlds = worlds
        self.settings = worlds[0].settings
        self.playthrough = {}
        self.entrance_playthrough = {}
        self.locations = {}
        self.entrances = []
        self.metadata = {}
        self.required_locations = {}
        self.hints = {world.id: {} for world in worlds}
        self.file_hash = []


    def build_file_hash(self):
        dist_file_hash = self.settings.distribution.file_hash
        for i in range(5):
            self.file_hash.append(random.randint(0,31) if dist_file_hash[i] is None else HASH_ICONS.index(dist_file_hash[i]))


    def parse_data(self):
        for (sphere_nr, sphere) in self.playthrough.items():
            sorted_sphere = [location for location in sphere]
            sort_order = {"Song": 0, "Boss": -1}
            sorted_sphere.sort(key=lambda item: (item.world.id * 10) + sort_order.get(item.type, 1))
            self.playthrough[sphere_nr] = sorted_sphere

        self.locations = {}
        for world in self.worlds:
            spoiler_locations = [location for location in world.get_locations() if not location.locked and location.type != 'GossipStone']
            spoiler_locations.sort(key=lambda item: sort_locations.index(str(item)))
            self.locations[world.id] = OrderedDict([(str(location), location.item) for location in spoiler_locations])

        entrance_sort_order = {"OwlDrop": 0, "Overworld": -1, "Dungeon": -2, "SpecialInterior": -3, "Interior": -3, "Grotto": -4, "Grave": -4, "SpecialGrave": -4}
        for (sphere_nr, sphere) in self.entrance_playthrough.items():
            sorted_sphere = [entrance for entrance in sphere]
            sorted_sphere.sort(key=lambda entrance: entrance_sort_order.get(entrance.type, 1))
            sorted_sphere.sort(key=lambda entrance: entrance.name)
            sorted_sphere.sort(key=lambda entrance: entrance.world.id)
            self.entrance_playthrough[sphere_nr] = sorted_sphere

        self.entrances = {}
        for world in self.worlds:
            spoiler_entrances = [entrance for entrance in world.get_entrances() if entrance.shuffled and entrance.primary]
            spoiler_entrances.sort(key=lambda entrance: entrance.name)
            spoiler_entrances.sort(key=lambda entrance: entrance_sort_order.get(entrance.type, 1))
            self.entrances[world.id] = spoiler_entrances
